# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1941dcbad833bdcfe99ff6aa8224122386156f391ccca7baf3c8df43f11c807c7c1e09bef7757bef01e30e085c6e6ca39a8d1a9f6cca0f2c793c8070a4d6b54

test:
  secret_key_base: d73e3959b754910b3cb78100a05b178c16c02e7cb3d021961afe7f044c997f4a98068615fbb2de3f0fc32ffa5a651ade727bb09dd7ae60dd197e99bafde92392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
